### PR TITLE
Notify CSOL-site when a badge claim is issued, to allow emailing

### PR DESCRIPTION
**Pull request by ghost**
CSOL-site will be notified when an issuer creates a badge claim through the /issuer interface.

Adds environment variable OPENBADGER_NOTIFICATION_WEBHOOK, which should be set to point at the path /notify/claim of wherever CSOL-site is.  e.g. http://localhost:3000/notify/claim.

### CODE REVIEW

**Comment by toolness** [comment]
By the way, I think the travis CI also failed in a similar way on another pull request ... but I am completely and utterly baffled as to how it could possibly fail.

**Comment by toolness** [comment]
Hey, I looked into the travis CI error and it's definitely not your fault. All the tests likely pass with your changes, but the travis CI error is due to a mongoose error that's thrown only on some test runs but not others. So worry not about it, I will fixit in a separate PR!

**Comment by ghost** [comment]
Ah, phat.  Thanks, yo.

**Comment by toolness** [comment]
Yep. I've reported the older travis failure as #198 and just fixed it.

However, the travis failure that just happened from building  613301f, in which the `Badge#reserveAndNotify creates reserved claim code` test is getting an `ECONNREFUSED` error, is unrelated, and I think that one might actually be yours to fix. ;)

**Comment by ghost** [comment]
Alright, added a rudimentary fake webhook that gets used when testing and when in development mode with no OPENBADGER_NOTIFICATION_WEBHOOK not set.  This fixes the broken test and should be a little more forgiving in general.

**Comment by toolness** [comment]
Cool. It would be bad ass if there were tests for `notifyOfReservedClaim()`, I guess, but otherwise this looks great.

**Pull request merged**
