### PR TITLE
Address performance issues on front page

### PR DESCRIPTION
**Pull request by brianloveswords**
This implements a few of strategies to performance. On the default, "show everything" page I went from ~6 second response times to ~900ms. On the paginated pages, responses are close to instantaneous.
- **Don't populate programs for issuers.** We aren't using them, and populations are expensive.
- **Only pull the data we need from the database.** For badges, that's `name`, `shortname`, and `program` (for population). For issuers, all we need is `name`.
- **Implement cheap pagination.** I set a default of 50 items, added some "next" and "previous" buttons to the frontend and called it a day. I also added a "show all" link to revert to previous behavior of listing everything. Ideally, I'd also add a search functionality but this is quick & dirty optimization, not perfect.

### CODE REVIEW

**Comment by cmcavoy** [comment]
I'd be a lot better with this if we had search...it's going to be really hard to find a badge...unless I'm misreading it? With pages I'm going to have to roll through each page...right?

**Comment by brianloveswords** [comment]
Screencap of pagination

pages

**Comment by brianloveswords** [comment]
Yep, you would. But there's the "show all" fallback, which reverts to previous behavior.

**Comment by brianloveswords** [comment]
Given an hour (or less) I could probably implement a janky search, but I figured this was better than nothing given the immediate pain.

**Comment by brianloveswords** [comment]
I could also add options for changing the per-page amount (though you can always fiddle with the query string). 100 or 200 per page probably wouldn't be so painful and there'd be real performance benefit.

**Comment by cmcavoy** [comment]
nope...i see the infinity now (deep). MEGRE IT. AND LAUNCH IT. 

merge even.

**Comment by brianloveswords** [comment]
I love finding uses for `Infinity`.

**Pull request merged**
