### PR TITLE
Only recommend online skill badges.

### LINKED ISSUE #252: Recommend only online badges
For CSOL - the recommendation system should only suggest badges that are categorized as 'online'.

### PR DESCRIPTION
**Pull request by brianloveswords**
Fixes #252 

@cmcavoy to review. Note that this means that if the user has completed all of the online skill badges, that user will get no recommendations.

### CODE REVIEW

**Comment by cmcavoy** [comment]
So...do you think it would be unreasonable on the CSOL side to make this call, but if no recommendations come back make a second call to get recommendations from the badge-themed recommendation endpoint?

**Comment by brianloveswords** [comment]
@cmcavoy, it'd be easier to just fix the API to return other badges if the recommendations filter strips out everything but I'm not sure what's intended by the ticket. It's an open question for @threeqube, @carlacasilli and @erinknight.

**Comment by erinknight** [comment]
If I understand this correctly, if a kid has earned all the science online badges, we just say, "you earned them all" and return nothing. That's fine, I think we handle this with copy. 

We can just say "You've got them all! Check out /explore for other programs, or try some badges from another category"

**Comment by brianloveswords** [comment]
@erinknight yep, that sounds good to me then.

**Pull request merged**
