### PR TITLE
Add endpoints for adding, revoking badges.

### PR DESCRIPTION
**Pull request by brianloveswords**
- Add an endpoint for directly awarding badges
- Add an endpoint for directly revoking badges
- Update mongoose from 3.2.1 to 3.6.7
- Fix `api.auth`: flip conditional so parameters are only sought in `req.query` if method is GET. Out of the common HTTP methods, POST, PATCH, PUT and DELETE all end up sticking the parameters in `req.body`, and GET is the only one that pulls params from the query string, so we should default to using `req.body` unless the method is GET.

### CODE REVIEW

**Comment by brianloveswords** [comment]
@andrewhayward, @stenington, @toolness whoever gets to it first, quick sanity check on this PR.

**Comment by cmcavoy** [comment]
will we be able to restrict some end points to certain jwt tokens? we're opening openbadger to a few different users, so we might need to consider it.

**Comment by brianloveswords** [comment]
@cmcavoy I was thinking about that. Here's how I think it it could work:
- Issuer X registers, gets a unique identifier (e.g., `issuer-x`) and a unique secret (`shh-secret`)
- When they create a JWT, they set the `iss` field to their unique ID and they sign the token with their secret.
- When we get a JWT, the first thing we do is unpack the payload without attempting to verify the signature (this will require a change to `jwt-simple`, or we can switch to using my `node-jws` library). We use the `iss` field to lookup the corresponding secret, then we use that to attempt to verify the JWT.
- We can also register "capabilitiess" for certain issuers, and we can make `api.auth` can take another option to specify which capabilities are required for certain routes.

**Comment by brianloveswords** [comment]
Ah, so `jwt-simple`'s `decode` function takes an undocumented third option, `noVerify`: https://github.com/hokaccha/node-jwt-simple/blob/master/lib/jwt.js#L46. So we won't have to submit a patch or switch it out.

**Comment by stenington** [comment]
Looks good!

**Comment by cmcavoy** [comment]
@brianloveswords your response to my comment earns a :+1:

**Pull request merged**
