### PR TITLE
Be graceful if badge has no categories.

### LINKED ISSUE #181: /v2/badge/:shortname/recommendations error
I'm getting this hitting `/v2/badge/:shortname/recommendations`:

```
/Users/mlarsson/Work/checkouts/openbadger/node_modules/mongoose/lib/utils.js:413
        throw err;
              ^
TypeError: Cannot call method 'filter' of undefined
    at Promise.Badge.getSimilar (/Users/mlarsson/Work/checkouts/openbadger/models/badge.js:529:21)
    at Promise.<anonymous> (/Users/mlarsson/Work/checkouts/openbadger/node_modules/mongoose/node_modules/mpromise/lib/promise.js:157:8)
    at Promise.EventEmitter.emit (events.js:88:17)
    at Promise.emit (/Users/mlarsson/Work/checkouts/openbadger/node_modules/mongoose/node_modules/mpromise/lib/promise.js:79:38)
    at Promise.reject (/Users/mlarsson/Work/checkouts/openbadger/node_modules/mongoose/node_modules/mpromise/lib/promise.js:106:15)
    at Promise.error (/Users/mlarsson/Work/checkouts/openbadger/node_modules/mongoose/lib/promise.js:89:15)
    at cb (/Users/mlarsson/Work/checkouts/openbadger/node_modules/mongoose/lib/query.js:1668:29)
    at exports.tick (/Users/mlarsson/Work/checkouts/openbadger/node_modules/mongoose/lib/utils.js:408:16)
    at Cursor.toArray (/Users/mlarsson/Work/checkouts/openbadger/node_modules/mongoose/node_modules/mongodb/lib/mongodb/cursor.js:156:22)
    at Cursor.nextObject.self.queryRun (/Users/mlarsson/Work/checkouts/openbadger/node_modules/mongoose/node_modules/mongodb/lib/mongodb/cursor.js:611:39)
```

### PR DESCRIPTION
**Pull request by brianloveswords**
Fixes #181

`getSimilar` was assuming there would always be at least one STEAM category associated with a badge. That was not a good assumption.

Note: this was actually fixed earlier, by 7ef55c228165fc8e02b45314c3a2a4d6fd5cc24f, but the "fix" still passed back an error. This is more graceful in that it detects if there are no categories early and calls back with an empty set.

### CODE REVIEW

**Comment by brianloveswords** [comment]
I'm gonna merge this.

**Comment by threeqube** [comment]
Wait, I'm fairly certain each badge is associated with at least one STEA or M category. @carlacasilli can you confirm? 

If we've made each badge associated with a STEAM category, then what does it mean if there are badges with no categories?

**Comment by cmcavoy** [comment]
Some of the test badges were created before STEAM categories. Brian is just
adding this so that errors don't take down the server.

On Thu, Jun 6, 2013 at 7:20 PM, threeqube notifications@github.com wrote:

> Wait, I'm fairly certain each badge is associated with at least one STEA
> or M category. @carlacasilli https://github.com/carlacasilli can you
> confirm?
> 
> If we've made each badge associated with a STEAM category, then what does
> it mean if there are badges with no categories?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/openbadger/pull/200#issuecomment-19082512
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com

**Comment by threeqube** [comment]
Sounds good. :+1:

**Pull request merged**
