### PR TITLE
Allow issuers to award badges with evidence attached

### LINKED ISSUE #122: Issue a badge to a single user, include evidence
Allow a mentor to issue a badge and include evidence.

### PR DESCRIPTION
**Pull request by toolness**
This is an attempt to resolve #122.

We're doing this by associating uploaded evidence with the [reserved claim codes](https://github.com/mozilla/openbadger/pull/185) that are created when badges are issued from OpenBadger.

When the API client (e.g. CSOL-site) is notified of a new reserved claim code via webhook, it will also check to see if there's any evidence items attached; if so, it will be responsible for downloading all the evidence from OpenBadger before redeeming the code. We need to do all this because the API client is the only entity that knows about evidence, manipulates it as needed (via e.g. video transcoding or image resizing), and presents it in an intelligible way to users.

Things that need to be done in OpenBadger:
- [x] Add a temporary evidence schema that hangs off the claim code schema.
- [x] Add methods to put/get/delete temporary evidence.
- [x] Add documentation for AWS-related environment variables to `README.md`.
- [x] Add a health check for AWS-related functionality.
- [x] Add metadata about how many evidence items a reserved claim code has to relevant API endpoint(s).
- [x] Add an authenticated API route that allows a single evidence item to be streamed to the client with the appropriate MIME type.
- [x] Ensure that redeeming or deleting a claim code also destroys its temporary evidence.
- [x] Document the new API routes in `docs/api.md`.
- [x] Add a view (or modify an existing one) that allows temporary evidence to be uploaded as files, and add/modify the corresponding route.

### CODE REVIEW

**Comment by toolness** [comment]
Ok, I think this is just about good to go.

One thing I just changed, though, is that temporary evidence is only reachable before a claim code is redeemed. Said evidence is automatically destroyed upon claim code redemption. Hopefully that's cool with CSOL-site.

@christensenep, should we modify the webhook to also tell the client how many evidence items are associated with the new reserved claim code? Or should CSOL-site ping `/v2/unclaimed` to discover that?

**Comment by ghost** [comment]
I guess it's mostly a philosophical decision, though given that the evidence "belongs" to the claim code in some sense, I think it makes sense to add this information to the webhook directly.

**Comment by cmcavoy** [comment]
I merged this locally, and tests fail. Can you rebase?

**Comment by cmcavoy** [comment]
@toolness can you rebase?

**Comment by cmcavoy** [comment]
@toolness in testing in staging, I can see a claim code being sent to me, but I never get an email to claim it.

**Comment by toolness** [comment]
Yeah, this is only the openbadger side of things. Csol-site needs to do the other half, which involves getting the evidence, putting it somewhere the user can see it, and then emailing them or auto-awarding the badge as needed.

This message was typed with haste on a tiny keyboard with no tactile feedback.

**Comment by cmcavoy** [comment]
I opened a ticket on the CSOL side, mozilla/csol-site#617 but am wondering
if this is just plugging this into the existing issue a claim code
notification flow for now? Other than evidence, it's exactly the
same...right?

On Mon, Jun 17, 2013 at 1:27 PM, Atul Varma notifications@github.comwrote:

> Yeah, this is only the openbadger side of things. Csol-site needs to do
> the other half, which involves getting the evidence, putting it somewhere
> the user can see it, and then emailing them or auto-awarding the badge as
> needed.
> 
> This message was typed with haste on a tiny keyboard with no tactile
> feedback.
> 
> On Jun 17, 2013, at 2:18 PM, Chris McAvoy notifications@github.com
> wrote:
> 
> > @toolness in testing in staging, I can see a claim code being sent to
> > me, but I never get an email to claim it.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/openbadger/pull/222#issuecomment-19564466
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com

**Comment by ghost** [comment]
Yeah, I think it actually should have sent an email (or auto-awarded the badge), though it doesn't handle the evidence yet.  I'll look into why that might have happened.

**Comment by ghost** [comment]
Ah, ok, it looks like the issues in staging were related to the circular referencing between openbadger-hooks and openbadger, which were just fixed with this PR: https://github.com/mozilla/CSOL-site/pull/613.  So I think we're good now.

**Pull request merged**
