### PR TITLE
Step up our logging game

### LINKED ISSUE #217: Figure out how to get logs in a format for Graylog (loggins)
[Winston graylog transport](https://github.com/flatiron/winston#graylog2-transport)

### PR DESCRIPTION
**Pull request by brianloveswords**
Fixes #217

### CODE REVIEW

**Comment by brianloveswords** [comment]
The Makefile has been updated so the default start server task automatically pipes through a formatter – just running `node app.js` will spit out raw json for every event.

The raw logs look like this
log

The formatted logs look like this:
log

When piping through `bin/messina` to send to Graylog, it gets parsed something like this:
log

`bin/messina` also echos out what's being put in, so it's entirely possible to do `node app.js | bin/messina | bunyan` to get formatted logs on the console as well as aggregation through graylog.

**Comment by brianloveswords** [comment]
Okay, this is pretty much ready I think. 

@cmcavoy, @jdotpz to review, @toolness to chastise me for not including tests (I still want modularize & test `bin/messina`, but I didn't want to have good logs wait on it).

**Comment by jdotpz** [comment]
furiousclap

cc @jbuck !

**Comment by jdotpz** [comment]
Drats, the one big doh is that using Foreman, it adds about 19 characters to the line, and I have not yet found a good combination of cut, passing variables, and getting gelf working.

foreman start -f Procfile|cut -c19- | GRAYLOG_HOST="loggins.mofoprod.net" GRAYLOG_PORT=12201 GRAYLOG_FACILITY="gelf" ./bin/messina

that works!!  Yeah, just not in upstart...yet.

**Pull request merged**
